# Generated by Django 2.2.4 on 2019-11-25 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kurye', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firma',
            name='pin',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.CreateModel(
            name='WSClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(default='', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wskurye', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
