# Generated by Django 2.2.4 on 2019-12-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurye', '0002_auto_20191217_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courier',
            name='registered_restaurants',
        ),
        migrations.AddField(
            model_name='courier',
            name='registered_restaurants',
            field=models.ManyToManyField(to='kurye.Restaurant'),
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='registered_couriers',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='registered_couriers',
            field=models.ManyToManyField(to='kurye.Courier'),
        ),
    ]
