# Generated by Django 2.2.4 on 2019-11-08 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kurye', '0002_grup'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Grup',
            new_name='AnaFirma',
        ),
        migrations.RenameField(
            model_name='anafirma',
            old_name='grup_adi',
            new_name='anafirma_adi',
        ),
    ]
