# Generated by Django 2.2.4 on 2019-11-08 11:05

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kurye', '0003_auto_20191108_0755'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma_adi', models.CharField(max_length=80)),
                ('adres', models.TextField()),
                ('mahalle', models.CharField(max_length=80)),
                ('ilce', models.CharField(max_length=80)),
                ('il', models.CharField(max_length=80)),
                ('enlem', models.DecimalField(decimal_places=12, default='0.0', max_digits=16)),
                ('boylam', models.DecimalField(decimal_places=12, default='0.0', max_digits=16)),
                ('motorcular', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('belge_1', models.ImageField(blank=True, null=True, upload_to='belge_1/%Y/%m/%d/')),
                ('belge_2', models.ImageField(blank=True, null=True, upload_to='belge_2/%Y/%m/%d/')),
                ('belge_3', models.ImageField(blank=True, null=True, upload_to='belge_3/%Y/%m/%d/')),
                ('belge_4', models.ImageField(blank=True, null=True, upload_to='belge_4/%Y/%m/%d/')),
                ('belge_5', models.ImageField(blank=True, null=True, upload_to='belge_5/%Y/%m/%d/')),
                ('belge_6', models.ImageField(blank=True, null=True, upload_to='belge_6/%Y/%m/%d/')),
                ('belge_7', models.ImageField(blank=True, null=True, upload_to='belge_7/%Y/%m/%d/')),
                ('belge_8', models.ImageField(blank=True, null=True, upload_to='belge_8/%Y/%m/%d/')),
                ('anafirma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kurye.AnaFirma')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='boylam',
            field=models.DecimalField(decimal_places=12, default='0.0', max_digits=16),
        ),
        migrations.AddField(
            model_name='user',
            name='enlem',
            field=models.DecimalField(decimal_places=12, default='0.0', max_digits=16),
        ),
        migrations.AddField(
            model_name='user',
            name='pic_profile',
            field=models.ImageField(blank=True, null=True, upload_to='pic_profile/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='user',
            name='tipi',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='durum',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.CreateModel(
            name='Teslimat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zaman', models.DateTimeField(auto_now=True)),
                ('teslim_edildi', models.BooleanField(blank=True)),
                ('odeme_alindi', models.BooleanField(blank=True)),
                ('teslim_edilmedi_sebep', models.CharField(default='0', max_length=2)),
                ('odeme_alinmadi_sebep', models.CharField(default='0', max_length=2)),
                ('odeme_alinmadi_sebep_adi', models.CharField(max_length=20)),
                ('odeme_alinmadi_sebep_soyadi', models.CharField(max_length=20)),
                ('odeme_alinmadi_sebep_tel', models.CharField(max_length=12)),
                ('odeme_alinmadi_sebep_adres', models.CharField(max_length=60)),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teslimat_firma', to='kurye.Firma')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teslimat', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Islemler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zaman', models.DateTimeField(auto_now=True)),
                ('islem', models.CharField(default='0', max_length=2)),
                ('sos_sebep', models.CharField(default='0', max_length=2)),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='islem_firma', to='kurye.Firma')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='islem', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bildirim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipi', models.CharField(default='0', max_length=2)),
                ('viewed', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bildirim', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bahsis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zaman', models.DateTimeField(auto_now=True)),
                ('miktar', models.DecimalField(decimal_places=2, max_digits=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bahsis', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
