# Generated by Django 2.2.4 on 2019-11-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurye', '0003_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pin',
            field=models.CharField(default='', max_length=6),
        ),
    ]
