# Generated by Django 2.2.4 on 2019-12-17 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kurye', '0004_auto_20191217_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_type',
            new_name='process_type',
        ),
    ]
