# Generated by Django 2.2.4 on 2019-11-08 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kurye', '0004_auto_20191108_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bildirim',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='bildirim', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
