# Generated by Django 2.2.4 on 2019-12-01 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kurye', '0005_auto_20191130_0837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firma',
            name='kayitli_motorcular',
        ),
        migrations.AddField(
            model_name='user',
            name='sira',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='KayitliMotorcular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kayitli_motocular', to='kurye.Firma')),
                ('motorcu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='motorcu_kayit', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
