# Generated by Django 2.2.4 on 2019-12-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurye', '0005_auto_20191217_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='self_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
