# Generated by Django 2.2.4 on 2019-11-08 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurye', '0005_auto_20191108_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aktif',
            field=models.BooleanField(default=True),
        ),
    ]
