# Generated by Django 2.2.4 on 2019-12-01 19:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurye', '0006_auto_20191201_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='firma',
            name='allow_self_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='firma',
            name='kayitli_motorcular',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='user',
            name='kaydolunan_restoranlar',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
        migrations.DeleteModel(
            name='KayitliMotorcular',
        ),
    ]
