# Generated by Django 2.2.4 on 2019-11-17 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kurye', '0006_user_aktif'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fiyat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_motorcu', models.PositiveIntegerField(default=0)),
                ('fiyat', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='firma',
            name='tel_no',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='firma',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='device_id',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='device_platform',
            field=models.CharField(choices=[('0', 'Android'), ('1', 'IOS')], default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='user',
            name='tel_no',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.CreateModel(
            name='FaturaToplam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yil', models.PositiveIntegerField(default=0)),
                ('ay', models.PositiveIntegerField(default=0)),
                ('odendi', models.BooleanField(blank=True)),
                ('tutar', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faturatoplam', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FaturaDetay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yil', models.PositiveIntegerField(default=0)),
                ('ay', models.PositiveIntegerField(default=0)),
                ('max_motorcu', models.PositiveIntegerField(default=0)),
                ('standart_ek', models.BooleanField(blank=True)),
                ('ek_kisi', models.PositiveIntegerField(default=0)),
                ('ek_toplam', models.PositiveIntegerField(default=0)),
                ('standart_tutar', models.PositiveIntegerField(default=0)),
                ('ek_tutar', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faturadetay', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EkFiyat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ek_motorcu', models.PositiveIntegerField(default=0)),
                ('fiyat', models.PositiveIntegerField(default=0)),
                ('max_motorcu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ek_fiyat', to='kurye.Fiyat')),
            ],
        ),
        migrations.CreateModel(
            name='ArtiMotorcu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_motorcu', models.PositiveIntegerField(default=0)),
                ('gecen_motorcu_adedi', models.PositiveIntegerField(default=0)),
                ('zaman', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artimotorcu', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
