# Generated by Django 2.2.4 on 2019-12-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurye', '0006_delivery_self_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture_abs_url',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
