# Generated by Django 2.2.4 on 2019-12-05 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurye', '0007_auto_20191201_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='teslimat',
            name='onay',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='device_id',
            field=models.CharField(default='0', max_length=40),
        ),
    ]
