# Generated by Django 2.2.4 on 2019-11-17 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kurye', '0007_auto_20191117_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firma',
            name='id',
        ),
        migrations.AlterField(
            model_name='firma',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
