# Generated by Django 2.2.4 on 2019-12-18 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kurye', '0007_user_profile_picture_abs_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profile_picture_abs_url',
            new_name='pic_profile_abs_url',
        ),
    ]
