# Generated by Django 2.2.4 on 2019-12-05 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kurye', '0008_auto_20191205_0647'),
    ]

    operations = [
        migrations.AddField(
            model_name='teslimat',
            name='adet',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teslimat',
            name='gecerli_adet',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='IslemTeslimat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zaman', models.DateTimeField(auto_now=True)),
                ('islem_tipi', models.BooleanField(blank=True)),
                ('odeme_alindi', models.BooleanField(blank=True)),
                ('teslim_edilmedi_sebep', models.CharField(default='0', max_length=2)),
                ('odeme_alinmadi_sebep', models.CharField(default='0', max_length=2)),
                ('odeme_alinmadi_sebep_adi', models.CharField(max_length=20)),
                ('odeme_alinmadi_sebep_soyadi', models.CharField(max_length=20)),
                ('odeme_alinmadi_sebep_tel', models.CharField(max_length=12)),
                ('odeme_alinmadi_sebep_adres', models.CharField(max_length=60)),
                ('teslimat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teslimat', to='kurye.Teslimat')),
            ],
        ),
    ]
