# Generated by Django 2.2.4 on 2019-12-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurye', '0008_auto_20191218_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='registered_restaurants',
            field=models.ManyToManyField(blank=True, null=True, to='kurye.Restaurant'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='registered_couriers',
            field=models.ManyToManyField(blank=True, null=True, to='kurye.Courier'),
        ),
    ]
