# Generated by Django 2.2.4 on 2019-11-18 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kurye', '0008_auto_20191117_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Il',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('il', models.CharField(default='İstanbul', max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Ilce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilce', models.CharField(default='Kadıköy', max_length=80)),
                ('il', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ilce_il', to='kurye.Il')),
            ],
        ),
        migrations.CreateModel(
            name='Mahalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mahalle', models.CharField(default='Fenerbahçe', max_length=80)),
                ('ilce', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mahalle_ilce', to='kurye.Ilce')),
            ],
        ),
    ]
