# Generated by Django 2.2.4 on 2019-12-05 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurye', '0009_auto_20191205_0712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='islemteslimat',
            name='odeme_alindi',
        ),
        migrations.RemoveField(
            model_name='teslimat',
            name='odeme_alindi',
        ),
        migrations.RemoveField(
            model_name='teslimat',
            name='odeme_alinmadi_sebep',
        ),
        migrations.RemoveField(
            model_name='teslimat',
            name='odeme_alinmadi_sebep_adi',
        ),
        migrations.RemoveField(
            model_name='teslimat',
            name='odeme_alinmadi_sebep_adres',
        ),
        migrations.RemoveField(
            model_name='teslimat',
            name='odeme_alinmadi_sebep_soyadi',
        ),
        migrations.RemoveField(
            model_name='teslimat',
            name='odeme_alinmadi_sebep_tel',
        ),
        migrations.RemoveField(
            model_name='teslimat',
            name='teslim_edildi',
        ),
        migrations.RemoveField(
            model_name='teslimat',
            name='teslim_edilmedi_sebep',
        ),
        migrations.AddField(
            model_name='islemteslimat',
            name='sos_kaldir_sebep',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='islemteslimat',
            name='sos_sebep',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.DeleteModel(
            name='Islemler',
        ),
    ]
