# Generated by Django 2.2.4 on 2019-11-19 08:23

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurye', '0009_il_ilce_mahalle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firma',
            name='motorcular',
        ),
        migrations.AddField(
            model_name='firma',
            name='kayitli_motorcular',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='aktif_firma',
            field=models.IntegerField(default=0),
        ),
    ]
