# Generated by Django 2.2.4 on 2019-12-19 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kurye', '0010_auto_20191219_0625'),
    ]

    operations = [
        migrations.CreateModel(
            name='WSClients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(default='', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wsclients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
