# Generated by Django 2.2.4 on 2019-12-19 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kurye', '0011_wsclients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courier',
            old_name='active_worker',
            new_name='worker_active',
        ),
    ]
