# Generated by Django 2.2.4 on 2019-12-09 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kurye', '0011_auto_20191208_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teslimat',
            name='user',
        ),
        migrations.AddField(
            model_name='teslimat',
            name='kurye',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teslimat', to=settings.AUTH_USER_MODEL),
        ),
    ]
