# Generated by Django 2.2.4 on 2019-12-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurye', '0012_auto_20191219_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='active_couriers',
            field=models.ManyToManyField(blank=True, related_name='active_couriers', to='kurye.Courier'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='registered_couriers',
            field=models.ManyToManyField(blank=True, related_name='registered_couriers', to='kurye.Courier'),
        ),
    ]
