# Generated by Django 2.2.4 on 2019-12-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurye', '0012_auto_20191209_0822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teslimat',
            name='sos_kaldir_sebep',
        ),
        migrations.RemoveField(
            model_name='teslimat',
            name='sos_sebep',
        ),
        migrations.AddField(
            model_name='islemteslimat',
            name='sos_kaldir_sonuc',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='islemteslimat',
            name='sos_sebep',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='islemteslimat',
            name='islem_tipi',
            field=models.CharField(default='0', max_length=2),
        ),
    ]
