# Generated by Django 2.2.4 on 2019-12-10 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurye', '0013_auto_20191209_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='bildirim',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
