# Generated by Django 2.2.4 on 2020-01-03 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kurye', '0013_auto_20191222_1859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='adress',
            new_name='address',
        ),
    ]
