# Generated by Django 2.2.4 on 2019-12-10 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kurye', '0014_bildirim_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bildirim',
            old_name='user',
            new_name='receiver',
        ),
    ]
