# Generated by Django 2.2.4 on 2020-01-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurye', '0014_auto_20200103_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courier',
            name='city',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='courier',
            name='district',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='courier',
            name='own_motocycle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courier',
            name='town',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
