# Generated by Django 2.2.4 on 2020-01-07 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kurye', '0015_auto_20200106_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district',
            old_name='Town',
            new_name='town',
        ),
    ]
