# Generated by Django 2.2.4 on 2019-12-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurye', '0019_user_aktif_teslimat'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aktif_islem',
            field=models.IntegerField(default=0),
        ),
    ]
