# Generated by Django 2.2.4 on 2019-12-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurye', '0020_user_aktif_islem'),
    ]

    operations = [
        migrations.AddField(
            model_name='islemteslimat',
            name='tel_no',
            field=models.CharField(default='', max_length=10),
        ),
    ]
