# Generated by Django 2.2.4 on 2019-12-12 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kurye', '0021_islemteslimat_tel_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teslimat',
            name='firma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teslimat_firma', to=settings.AUTH_USER_MODEL),
        ),
    ]
