# Generated by Django 2.2.4 on 2019-12-12 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kurye', '0022_auto_20191212_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teslimat',
            name='firma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teslimat_firma', to='kurye.Firma'),
        ),
        migrations.AlterField(
            model_name='teslimat',
            name='kurye',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='teslimat', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
