# Generated by Django 2.2.4 on 2019-12-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurye', '0023_auto_20191212_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='teslimat',
            name='sos',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teslimat',
            name='sos_sonuc',
            field=models.CharField(default='0', max_length=2),
        ),
    ]
