# Generated by Django 2.2.4 on 2019-12-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurye', '0024_auto_20191212_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='islemteslimat',
            old_name='sos_kaldir_sonuc',
            new_name='sos_sonuc',
        ),
        migrations.AddField(
            model_name='teslimat',
            name='sos_sebep',
            field=models.CharField(default='0', max_length=2),
        ),
    ]
