# Generated by Django 2.2.4 on 2019-12-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurye', '0025_auto_20191212_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teslimat',
            name='sos',
            field=models.BooleanField(default=False),
        ),
    ]
