# Generated by Django 2.2.4 on 2019-12-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurye', '0026_auto_20191212_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='islemteslimat',
            name='boylam',
            field=models.DecimalField(decimal_places=12, default='0.0', max_digits=16),
        ),
        migrations.AddField(
            model_name='islemteslimat',
            name='enlem',
            field=models.DecimalField(decimal_places=12, default='0.0', max_digits=16),
        ),
        migrations.AddField(
            model_name='islemteslimat',
            name='tam_isim',
            field=models.CharField(default='', max_length=60),
        ),
    ]
