# Generated by Django 2.2.4 on 2019-12-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurye', '0027_auto_20191212_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='device_id',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
